//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by wsdl, Version=4.8.3928.0.
// 
namespace My.Contract.First {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.Web.Services.WebServiceBindingAttribute(Name="MaterialsEndpointServiceSoapBinding", Namespace="https://localhost:44368/WebService-Material.asmx/Materials")]
    public interface IMaterialsEndpointServiceSoapBinding {
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44368/WebService-Material.asmx/GetDeveloped", RequestElementName="GetDevelopedRequest", RequestNamespace="https://localhost:44368/WebService-Material.asmx/Materials", ResponseNamespace="https://localhost:44368/WebService-Material.asmx/Materials", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StringResponse")]
        stringResponse GetDeveloped(stringRequest StringRequest);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44368/WebService-Material.asmx/GetPurchased", RequestElementName="GetPurchasedRequest", RequestNamespace="https://localhost:44368/WebService-Material.asmx/Materials", ResponseNamespace="https://localhost:44368/WebService-Material.asmx/Materials", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StringResponse")]
        stringResponse GetPurchased(purchasedStringRequest PurchasedStringRequest);
        
        /// <remarks/>
        [System.Web.Services.WebMethodAttribute()]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("https://localhost:44368/WebService-Material.asmx/ReportStockLevels", RequestElementName="GetPurchasedRequest", RequestNamespace="https://localhost:44368/WebService-Material.asmx/Materials", ResponseElementName="GetPurchasedResponse", ResponseNamespace="https://localhost:44368/WebService-Material.asmx/Materials", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("StringResponse")]
        stringResponse ReportStockLevels(purchasedStringRequest PurchasedStringRequest);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://localhost:44368/WebService-Material.asmx/Materials")]
    public partial class stringRequest {
        
        private int umidField;
        
        private int aidField;
        
        /// <remarks/>
        public int umid {
            get {
                return this.umidField;
            }
            set {
                this.umidField = value;
            }
        }
        
        /// <remarks/>
        public int aid {
            get {
                return this.aidField;
            }
            set {
                this.aidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://localhost:44368/WebService-Material.asmx/Materials")]
    public partial class purchasedStringRequest {
        
        private int umidField;
        
        /// <remarks/>
        public int umid {
            get {
                return this.umidField;
            }
            set {
                this.umidField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="https://localhost:44368/WebService-Material.asmx/Materials")]
    public partial class stringResponse {
        
        private string stringMessageField;
        
        /// <remarks/>
        public string StringMessage {
            get {
                return this.stringMessageField;
            }
            set {
                this.stringMessageField = value;
            }
        }
    }
}
